/**
 * Rutas estáticas espejadas en GitHub Pages (cada una → index.html).
 * Fuente única para prepare-pages.ts y verificación CI.
 */
export const SPA_MIRROR_ROUTES: readonly string[] = [
  "login",
  "configurar",
  "ayuda",
  "glosario",
  "unirse",
  "unirse-qr",
  "completar-perfil",
  "panel",
  "operacion",
  "personal",
  "turnos",
  "cuentas",
  "qr-sitios",
  "mapa",
  "reportes",
  "notificaciones",
  "nomina",
  "configuracion",
  "clientes",
  "facturacion",
  "inventario",
  "integraciones",
  "negocio",
  "descargas",
  "pendientes",
  "supervision",
  "comunicacion",
  "equipo-admin",
  "informes",
  "master",
  "master/administradores",
  "master/trabajadores",
  "master/comunicacion",
  "master/roles",
  "master/informes",
  "master/informes-evento",
  "master/auditoria",
  "master/ayuda",
  "master/glosario",
  "master/panel",
  "master/configuracion",
  "master/personal",
  "master/cuentas",
  "master/operacion",
  "master/supervision",
  "master/turnos",
  "master/qr-sitios",
  "master/reportes",
  "master/nomina",
  "master/negocio",
  "master/notificaciones",
  "master/pendientes",
  "master/integraciones",
  "master/descargas",
  "worker",
  "worker/turnos",
  "worker/entrada",
  "worker/reportar",
  "worker/comunicacion",
  "worker/notificaciones",
  "worker/ayuda",
  "worker/glosario",
] as const;

/** Rutas críticas que CI debe verificar tras el build. */
export const SPA_CRITICAL_ROUTES: readonly string[] = [
  "descargas",
  "pendientes",
  "notificaciones",
  "worker/notificaciones",
  "worker/ayuda",
  "master/ayuda",
  "glosario",
  "master/glosario",
] as const;
